version: '{build}'
image: Visual Studio 2015
configuration: Release
install:
- cmd: |-
    dotnet restore
    dotnet build src/Facility.GeneratorApi.WebApi
build_script:
- cmd: |-
    dotnet build src\Facility.GeneratorApi.WebApi --configuration Release
test: off
