---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: generator-api
spec:
  maxReplicas: 4
  minReplicas: 2
  targetCPUUtilizationPercentage: 90
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: generator-api
